components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          format: uuid
          description: The unique identifier of the product.
        title:
          type: string
          description: The title of the product.
        description:
          type: string
          description: The description of the product.
        price:
          type: String
          description: The price of the product.
        thumbnail:
          type: array
          items:
            type: string
          description: The thumbnail of the product.
        code:
          type: string
          description: The code of the product.
        status:
          type: boolean
          description: The status of the product.
        stock:
          type: integer
          description: The stock of the product.
        category:
          type: string
          description: The category of the product.
        timestamp:
          type: string
          format: date-time
          description: The date and time when the product was created.
      required:
        - title
        - description
        - price
        - thumbnail
        - code
        - stock
        - category
      example:
          _id: 5f5b9e3e3d5f3e2b3d5f3e2b
          title: "Product Title"
          description: "Product Description"
          price: "100.00"
          thumbnail: ["thumbnail1.jpg", "thumbnail2.jpg"]
          code: "product-code"
          status: true
          stock: 100
          category: "product-category"
          timestamp: "2023-12-18T04:15:59.763+00:00"
